To Do List V 0.0.1
Iconica-Development/to_do_list pull request #1
Opened 2022-09-02 12:23 UTC by FlutterJorian

To do list with checklist on detailscreen

2022-09-02 13:06 UTC, Gorter-dev requested changes
Even iets om over na te denken:

Moet deze UI zo hard gekoppeld zijn aan de carousel?
Als dit ja is, lijkt het mij zinning om de onderliggende logica ook als service aan te bieden zodat je je eigen UI kan bouwen

2022-09-02 13:06 UTC, Gorter-dev commented on lib/to_do_list.dart
> +class ToDoList extends StatelessWidget {
Zelfde als bij carousel hier graag alleen exports

2022-09-02 13:06 UTC, Gorter-dev commented on lib/to_do_list.dart
> +    required this.tasks,
Documentatie

2022-09-02 13:06 UTC, Gorter-dev commented on lib/to_do_list_detail.dart
> +class ToDoListDetailTheme {
Docs

2022-09-02 13:06 UTC, Gorter-dev commented on lib/widgets/to_do_list_card.dart
> +  ToDoListCardTheme({
Docs

2022-09-09 08:51 UTC, FlutterJorian commented on lib/to_do_list_detail.dart
> +class ToDoListDetailTheme {
spreekt voor zich

2022-09-09 13:06 UTC, Gorter-dev approved these changes

2022-09-09 13:06 UTC, merged